#ifndef DISPLAYMANAGER_H
#define DISPLAYMANAGER_H

/* BeginDocumentation
 * Name: DisplayManager
 *
 * Description: Displays of multimeters
 *
 * Author: Pablo Martinez Cañada. University of Granada. CITIC-UGR. Spain.
 * <pablomc@ugr.es>
 *
 * SeeAlso: multimeter
 */

#include <sstream>
#include "multimeter.h"
#include "Retina.h"

using namespace cimg_library;
using namespace std;

class DisplayManager{
protected:
    // Image size
    int sizeX, sizeY;

    // Display parameters
     double displayZoom;
     double delay;
     int imagesPerRow;
     vector <bool> isShown;
     vector <double> margin;

    // Buffers of displays and images generated by each module
    vector <CImgDisplay*> displays;
    CImg<double>** intermediateImages;

    // Buffers of multimeters and their parameters
    vector <multimeter*> multimeters;
    vector <string> multimeterIDs;
    vector <string> moduleIDs;
    vector <int> multimeterType;

    // To select either temporal or spatial multimeter
    vector < vector <int> > multimeterParam;

    // Parameters of the LN multimeters
    vector <double> LNSegment;
    vector <double> LNInterval;
    vector <double> LNStart;
    vector <double> LNStop;
    const char * LNFile;

    // copy of input
    CImg <double> *inputImage;

    // Last row to display
    int last_row,last_col;
    //Color bars
    CImg <double> **bars;
    CImg <double> *templateBar;

    // Number of modules
    int numberModules;

    // Values allocated
    bool valuesAllocated;

    // Simulation step
    double simStep;


public:
    // Constructor, copy, destructor.
    DisplayManager(int x=1,int y=1);
    DisplayManager(const DisplayManager& copy);
    ~DisplayManager(void);

    void reset();

    // Allocate values
    bool allocateValues(int number,double tstep);

    // Set X and Y
    bool setSizeX(int x);
    bool setSizeY(int y);

    // Other Set functions
    void setZoom(double zoom);
    void setDelay(int displayDelay);
    void setImagesPerRow(int numberI);
    void setIsShown(bool value, int pos);
    void setMargin(double m, int pos);

    // Modify LN multimeter
    void modifyLN(string moduleID,double start,double stop);

    // Add display
    void addModule(int pos, string ID);

    // Add multimeter
    void addMultimeterTempSpat(string multimeterID, string moduleID, int param1, int param2, bool temporalSpatial, string Show, bool recordAllCells, double startTime);
    void addMultimeterLN(string multimeterID, string moduleID, int x, int y, double segment, double interval, double start, double stop, double rangePlot, string Show);

    // Update displays
    void updateDisplay(CImg <double> *input, Retina &retina, int step, double totalSimTime, double numberTrials,double totalNumberTrials);

    // Aux functions
    double findMin(CImg<double> *input);
    double findMax(CImg<double> *input);

    // Set Simulation step
    bool setSimStep(double value);

};

#endif // DISPLAYMANAGER_H
